spring:
    datasource:
        url: jdbc:h2:mem:trajetapi;DB_CLOSE_DELAY=-1
        driver-class-name: org.h2.Driver
        username: fred
        password:
        initialization-mode: always
        data: classpath:db-init/data.sql
    jpa:
        show-sql: true
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        properties: 
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format-sql: true
    h2:
        console:
            enabled: true